// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.31.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// The type `Pos` is not used by any `pub` functions, thus it is ignored.
// The type `RENDERERS` is not used by any `pub` functions, thus it is ignored.
// The type `RenderCommand` is not used by any `pub` functions, thus it is ignored.
// The type `RenderInfo` is not used by any `pub` functions, thus it is ignored.
// The type `RenderRequest` is not used by any `pub` functions, thus it is ignored.
// The type `RenderResponse` is not used by any `pub` functions, thus it is ignored.
// The type `SimpleContext` is not used by any `pub` functions, thus it is ignored.

String greet({required String name, dynamic hint}) =>
    RustLib.instance.api.greet(name: name, hint: hint);

Future<Uint8List> testRender(
        {required double x, required double y, dynamic hint}) =>
    RustLib.instance.api.testRender(x: x, y: y, hint: hint);
